### ISSUE TITLE
Plugin sidebar empty [0.12.2]

### ISSUE THREAD

**Issue by riesegarder** [1Axen/blink#10]
![image](https://github.com/1Axen/blink/assets/171559140/63f04067-9c49-4192-8925-72471fb15cba)
I'm unable to edit/generate anything because of this
Output has no errors

https://jumpshare.com/v/t4DAC5OoZi80guYwCAgi

**Comment by 1Axen** [comment]
Yikes, don't know how that one slipped through. I suggest downgrading to 0.12.1 for the time being, I'm not going to be able to release a fix until tomorrow around 2-3 PM EEST.

**Comment by 1Axen** [comment]
Issue has been resolved in [v0.12.3](https://github.com/1Axen/blink/releases/tag/v0.12.3).
