### ISSUE TITLE
Omitting "Data" field generates error

### ISSUE THREAD

**Issue by riesegarder** [1Axen/blink#11]
Noticed the omit Data field feature in the syntax, so I tried it out and got this:
![image](https://github.com/1Axen/blink/assets/171559140/80903041-476d-49f1-95b9-d1d18e894c28)
![image](https://github.com/1Axen/blink/assets/171559140/99d18706-557d-426b-9f4a-c155834c731d)
![image](https://github.com/1Axen/blink/assets/171559140/4f5597d6-80ac-49fa-92a9-5c92fc6d5e1a)

Editing the module and removing the comma fixes it, or just putting any valid type in the Data field.

**Comment by 1Axen** [comment]
Sorry for the late acknowledgment, GitHub didn't give me a notification about the issue being opened, I will look into it.

**Comment by 1Axen** [comment]
Thanks for the repot, issue is fixed in [v0.13.4](https://github.com/1Axen/blink/releases/tag/v0.13.4).
