### ISSUE TITLE
Typescript definitions do not append Promise<T> to functions that yield via promises

### ISSUE THREAD

**Issue by Awes-3** [1Axen/blink#14]
Assuming a config file with typescript definitions:
```
function doSomething {
    yield: Promise,
    data: u8,
    return: u8
}
``` 
The expected output is:
```typescript
export const doSomething: {
    invoke: (Value: number) => Promise<number>;
};
``` 
However, the current output is:
```typescript
export const doSomething: {
    invoke: (Value: number) => number;
};
``` 

Typescript has a Promise type built in, so the only change needed would be wrapping the return type in the built in Promise type

**Comment by 1Axen** [comment]
Resolved in 1fe6ea6
