### ISSUE TITLE
Blink generates invalid code when ranges are single numbers

### ISSUE THREAD

**Issue by Hexcede** [1Axen/blink#17]
When a range like `f64(0)` is specified, blink generates a check that has no `end`:
![image](https://github.com/user-attachments/assets/4406a327-8c13-4620-a50c-74530e4d1e1a)

Here is the same line with the range `f64(0..9007199254740992)`:
![image](https://github.com/user-attachments/assets/1a4d9637-0431-4420-97fb-00be53448d89)

**Comment by 1Axen** [comment]
This is intended behaviour, it doesn't make sense on things like numeric types but is very useful on buffers and vectors for enforcing exact an byte size, and an exact magnitude (for things like unit vectors).

I assume you're actually looking for a behaviour like unbounded ranges (which I saw you opened an issue about).

**Comment by 1Axen** [comment]
> I think you misunderstood, Blink is not generating the `end` syntax for the if statements when you specify an exact range (note the green box, the `end` is missing so the generated file is broken).

That's on me for hastily reading, I've fixed it in 9d14f61dc48c180b168ebf065c96a9776d28f25d.
Also released a new version with the fix: [v0.14.14](https://github.com/1Axen/blink/releases/tag/v0.14.14).
