### ISSUE TITLE
Blink should support unbounded ranges

### ISSUE THREAD

**Issue by Hexcede** [1Axen/blink#18]
Ranges such as `..0` and `0..` are not supported by blink. This makes it impossible to represent ranges that enclose all positive or all negative numbers for example.

**Comment by 1Axen** [comment]
Added support for this in 5109d0c95ad9a4aad941d0f5baafd4533e7d8853.
Included in the latest release: [v0.14.14](https://github.com/1Axen/blink/releases/tag/v0.14.14).
