### ISSUE TITLE
Allow struct field names that are also primitives

### ISSUE THREAD

**Issue by Hexcede** [1Axen/blink#19]
Blink, like Zap doesn't allow structs to have fields that are also the name of a primitive. As far as I am aware, this makes field names like `CFrame` or `Instance` impossible inside of a struct:
```c
struct Example {
    CFrame: CFrame<f32, f32>
}
```
![image](https://github.com/user-attachments/assets/cc2ba519-2007-4175-a8d3-f80bba4c70f0)

Making this work directly probably comes with some technical challenges, but allowing for some syntax such as one of the following would likely be sufficient:
![image](https://github.com/user-attachments/assets/dd3b749d-f14c-4502-8a2e-8983f1bb828b)
![image](https://github.com/user-attachments/assets/0b9f3736-a156-4f68-a635-4362c302e5cb)

**Comment by 1Axen** [comment]
Fixed in d1781e4d7ad48f007118e663118cbea2f5cc25c8
Available in the [latest release](https://github.com/1Axen/blink/releases/tag/v0.14.15)

**Comment by 1Axen** [comment]
I ended up settling on no extra syntax for it (no ""/[""]), the first snipped should correctly parse now.
