### ISSUE TITLE
Color3 uses 0-255 bounded range to write to buffers, but does not use Color3.fromRGB when reading

### ISSUE THREAD

**Issue by Awes-3** [1Axen/blink#22]
Currently, Color3.new is used to read serialized Color3 values. This should be switched to Color3.fromRGB as Color3.new does not support the 0-255 integer range for RGB values.

**Comment by 1Axen** [comment]
Fixed in cc40fec1eb62899d0a7228ad7e84d24d36187f55
Available in [latest release](https://github.com/1Axen/blink/releases/tag/v0.14.15)
