### ISSUE TITLE
Merged generic struct generates incorrect type information

### ISSUE THREAD

**Issue by Ardi7247** [1Axen/blink#24]
the following .blink file:
![image](https://github.com/user-attachments/assets/26ba6ed5-4b37-4590-9fe2-fba03025a8ff)
generates this type information:
![image](https://github.com/user-attachments/assets/e1daa883-1658-4fb6-836f-6dc8e7756860)
for some ungodly reason blink thinks that the name of the field is a type when merging..? wtf
something similar can be seen in one of the test sources:
https://github.com/1Axen/blink/blob/main/test/Sources/Test.blink#L129
outputs type information:
![image](https://github.com/user-attachments/assets/5b169761-2fa1-45fe-bdaf-507a45788284)

**Comment by 1Axen** [comment]
Fixed in #25
