### ISSUE TITLE
A type to send any generic data

### ISSUE THREAD

**Issue by ewd3v** [1Axen/blink#28]
Sometimes I can see myself in the situation of having to send some generic data to a client that I cannot in any sensible way create a schema for (as it may change, or just be completely dynamic). It would be handy to have some sort of type that you could assign to data like this (maybe "any", or "generic"?).

As this data can't be packed into buffers it could be sent in the same way as instances are. Adding this as a feature would allow you to send this type of data alongside with data that is packed into buffers, without having to create a whole seperate remote outside of blink just for the generic data.
As the type of this data can't be known it can't be typechecked at runtime either (rather the developer will have to do that), but I feel like the type name of "any" would already imply this.

**Comment by 1Axen** [comment]
You can use `unknown` for arbitrary data.

**Comment by ewd3v** [comment]
Oh? Sorry couldn't find it while reading the [docs](https://1axen.github.io/blink/syntax). Thanks!
